accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

app/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib import admin


from main.views import IndexPageView, ChangeLanguageView, new_book, log_pages, log_dash, activity, profile, act_unfollow, act_follow


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView, name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
]



urlpatterns += [
    path('newbook/', new_book, name='new_book'),
    path('logpages/', log_pages, name='log_pages'),
    path('logdash/', log_dash, name='log_dash'),

    path('activity/', activity, name='activity'),

    # url(r'^(?P<username>[^/]+)/activity/$', activity, name='activity'),
    url(r'^(?P<username>[^/]+)/$', profile, name='profile'),

    url(r'^(?P<username>[^/]+)/act_unfollow/$', act_unfollow, name='act_unfollow'),
    url(r'^(?P<username>[^/]+)/act_follow/$', act_follow, name='act_follow'),



]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/templates/layouts/default/DELETETHIS_SAVEHTML.html
{% load staticfiles %}
{% load i18n %}
{% load bootstrap4 %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="An example of Django project with basic user functionality.">
    <meta name="author" content="Yehor Smoliakov">

    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>Simple Django Login and Registration</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">{% trans 'Home' %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_profile' %}">{% trans 'Change profile' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a>
                </li>
            {% endif %}
        </ul>

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'change_language' %}">{% trans 'Change language' %}</a>
            </li>
        </ul>
    </div>

</nav>

<div class="container-fluid mt-3">

    {% bootstrap_messages %}

    {% block content %}
        No content.
    {% endblock %}

</div>

<script src="{% static 'vendor/jquery/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>

content/templates/layouts/default/landing.html
{% load static %}
{% load i18n %}
{% load bootstrap4 %}


<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- End Required meta tags -->
  <!-- Begin SEO tag -->
  <title> Starter Template | Looper - Bootstrap 4 Admin Theme </title>
  <meta property="og:title" content="Starter Template">
  <meta name="author" content="Beni Arisandi">
  <meta property="og:locale" content="en_US">
  <meta name="description" content="Responsive admin theme build on top of Bootstrap 4">
  <meta property="og:description" content="Responsive admin theme build on top of Bootstrap 4">
  <link rel="canonical" href="http://uselooper.com">
  <meta property="og:url" content="http://uselooper.com">
  <meta property="og:site_name" content="Looper - Bootstrap 4 Admin Theme">
  <script type="application/ld+json">
    {
      "name": "Looper - Bootstrap 4 Admin Theme",
      "description": "Responsive admin theme build on top of Bootstrap 4",
      "author":
      {
        "@type": "Person",
        "name": "Beni Arisandi"
      },
      "@type": "WebSite",
      "url": "",
      "headline": "Starter Template",
      "@context": "http://schema.org"
    }
  </script>
  <!-- End SEO tag -->
  <!-- FAVICONS -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static '/looperassets/apple-touch-icon.png' %}">
  <link rel="shortcut icon" href="{% static '/looperassets/favicon.ico' %}">
  <meta name="theme-color" content="#3063A0">
  <!-- End FAVICONS -->
  <script src="{% static '/looperassets/vendor/pace/pace.min.js' %}"></script>
  <!-- BEGIN BASE STYLES -->
  <link rel="stylesheet" href="{% static '/looperassets/vendor/pace/pace.min.css' %}">
  <link rel="stylesheet" href="{% static '/looperassets/vendor/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/looperassets/vendor/open-iconic/css/open-iconic-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/looperassets/vendor/fontawesome/css/fontawesome.all.css' %}">
  <!-- END BASE STYLES -->
  <!-- BEGIN THEME STYLES -->
  <link rel="stylesheet" href="{% static '/looperassets/stylesheets/main.min.css' %}">
  <link rel="stylesheet" href="{% static '/looperassets/stylesheets/custom.css' %}">
  <!-- END THEME STYLES -->
</head>
<body>
  <!-- .app -->
  <div class="app has-fullwidth">
    <!-- .app-header -->
    <header class="app-header">
      <!-- .top-bar -->
      <div class="top-bar">
        <!-- .top-bar-brand -->
        <div class="top-bar-brand">
          <a href="/">
            <img src="{% static '/looperassets/images/brand-inverse.png' %}" height="32" alt="">
          </a>
        </div>
        <!-- /.top-bar-brand -->
        <!-- .top-bar-list -->
        <div class="top-bar-list">
                    <!-- .top-bar-item -->
          <div class="top-bar-item px-2 d-md-none d-lg-none d-xl-none">
            <!-- toggle menu -->
            <a href="/">
              <img src="{% static '/looperassets/images/brand-inverse.png' %}" height="32" alt="">
            </a>
          </div>
        </div>


          <!-- /.top-bar-item -->
        </div>
        <!-- /.top-bar-list -->
      <!-- /.top-bar -->
    </header>
    <!-- /.app-header -->
    <!-- .app-aside -->

    <!-- /.app-aside -->
    <!-- .app-main -->
    <main class="app-main">
      <!-- .wrapper -->
      <div class="wrapper">
        <!-- .page -->
        <div class="page">
          <!-- .page-inner -->
          <div class="page-inner">
            <!-- .page-title-bar -->
            <header class="page-title-bar">




            </header>
            <!-- /.page-title-bar -->
            <!-- .page-section -->
            <div class="page-section">
              {% block content %}

              {% endblock %}
            </div>
            <!-- /.page-section -->
          </div>
          <!-- /.page-inner -->
        </div>
        <!-- /.page -->
      </div>
      <!-- /.wrapper -->
    </main>
    <!-- /.app-main -->
  </div>
  <!-- /.app -->
  <!-- BEGIN BASE JS -->
  <script src="{% static '/looperassets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static '/looperassets/vendor/bootstrap/js/popper.min.js' %}"></script>
  <script src="{% static '/looperassets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  <!-- END BASE JS -->
  <!-- BEGIN PLUGINS JS -->
  <script src="{% static '/looperassets/vendor/stacked-menu/stacked-menu.min.js' %}"></script>
  <script src="{% static '/looperassets/vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
  <!-- END PLUGINS JS -->
  <!-- BEGIN THEME JS -->
  <script src="{% static '/looperassets/javascript/main.min.js' %}"></script>
  <!-- END THEME JS -->
</body>

content/templates/layouts/default/page.html
{% load static %}
{% load i18n %}
{% load bootstrap4 %}


<head>

  <meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />


  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <!-- End Required meta tags -->
  <!-- Begin SEO tag -->
  <title> Ten Pages Main </title>
  <!-- <meta property="og:title" content="Starter Template">
  <meta name="author" content="Beni Arisandi">
  <meta property="og:locale" content="en_US">
  <meta name="description" content="Responsive admin theme build on top of Bootstrap 4">
  <meta property="og:description" content="Responsive admin theme build on top of Bootstrap 4">
  <link rel="canonical" href="http://uselooper.com">
  <meta property="og:url" content="http://uselooper.com">
  <meta property="og:site_name" content="Looper - Bootstrap 4 Admin Theme">
  <script type="application/ld+json">
    {
      "name": "Looper - Bootstrap 4 Admin Theme",
      "description": "Responsive admin theme build on top of Bootstrap 4",
      "author":
      {
        "@type": "Person",
        "name": "Beni Arisandi"
      },
      "@type": "WebSite",
      "url": "",
      "headline": "Starter Template",
      "@context": "http://schema.org"
    }
  </script> -->
  <!-- End SEO tag -->
  <!-- FAVICONS -->

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">


  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static '/looperassets/apple-touch-icon.png' %}">
  <link rel="shortcut icon" href="{% static '/looperassets/favicon.ico' %}">
  <!-- <meta name="theme-color" content="#3063A0"> -->
  <!-- End FAVICONS -->
  <!-- <script src="{% static '/looperassets/vendor/pace/pace.min.js' %}"></script> -->
  <!-- BEGIN BASE STYLES -->
  <!-- <link rel="stylesheet" href="{% static '/looperassets/vendor/pace/pace.min.css' %}"> -->
  <link rel="stylesheet" href="{% static '/looperassets/vendor/bootstrap/css/bootstrap.min.css' %}">
  <!-- <link rel="stylesheet" href="{% static '/looperassets/vendor/open-iconic/css/open-iconic-bootstrap.min.css' %}"> -->
  <!-- <link rel="stylesheet" href="{% static '/looperassets/vendor/fontawesome/css/fontawesome.all.css' %}"> -->
  <!-- END BASE STYLES -->
  <!-- BEGIN THEME STYLES -->
  <link rel="stylesheet" href="{% static '/looperassets/stylesheets/main.min.css' %}">
  <link rel="stylesheet" href="{% static '/looperassets/stylesheets/custom.css' %}">
  <!-- <link rel="stylesheet" href="{% static '/looperassets/vendor/datatables/extensions/buttons/buttons.bootstrap4.min.css' %}"> -->
  <!-- END THEME STYLES -->
  <style>

</style>
</head>
<body>
  <!-- .app -->
  <div class="app">
    <!-- .app-header -->
    <header class="app-header">
      <!-- .top-bar -->
      <div class="top-bar">
        <!-- .top-bar-brand -->
        <div class="top-bar-brand">
          <a href="/">
            <img src="{% static '/looperassets/images/brand-inverse.png' %}" height="32" alt="">
          </a>
        </div>
        <!-- /.top-bar-brand -->
        <!-- .top-bar-list -->
        <div class="top-bar-list">
                    <!-- .top-bar-item -->
          <div class="top-bar-item px-2 d-md-none d-lg-none d-xl-none">
            <!-- toggle menu -->
            <button class="hamburger hamburger-squeeze" type="button" data-toggle="aside" aria-label="Menu" aria-controls="navigation">
              <span class="hamburger-box">
                <span class="hamburger-inner"></span>
              </span>
            </button>
          </div>
        </div>


          <div class="top-bar-item top-bar-item-right px-0 d-none d-sm-flex">

            <div class="dropdown">
              <button class="btn-account d-none d-md-flex" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="user-avatar">
                  <img src="{% static '/looperassets/images/avatars/team4.jpg' %} " alt="">
                </span>
                <span class="account-summary pr-lg-4 d-none d-lg-block">
                  <span class="account-name">{{ request.user.username }}</span>
                  <!-- <span class="account-description">Marketing Manager</span> -->
                </span>
              </button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'profile' user.username %}">{% trans 'Profile' %}</a>

                {% if request.user.is_authenticated %}

                  <a class="dropdown-item" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>

                {% else %}

                  <a class="dropdown-item" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>

                {% endif %}

                <a class="dropdown-item" href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a>
                <a class="dropdown-item" href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a>


              </div>
              <!-- /.dropdown-menu -->
            </div>
            <!-- /.btn-account -->
          </div>
          <!-- /.top-bar-item -->
        </div>
        <!-- /.top-bar-list -->
      <!-- /.top-bar -->
    </header>
    <!-- /.app-header -->
    <!-- .app-aside -->
    <aside class="app-aside">
      <!-- .aside-content -->
      <div class="aside-content">
        <!-- .aside-header -->
        <header class="aside-header d-block d-md-none">
          <!-- .btn-account -->
          <button class="btn-account" type="button" data-toggle="collapse" data-target="#dropdown-aside">
            <span class="user-avatar user-avatar-lg">
              <img src="{% static '/looperassets/images/avatars/team4.jpg' %} " alt="">
            </span>
            <span class="account-icon">
              <span class="fa fa-caret-down fa-lg"></span>
            </span>
            <span class="account-summary">
              <span class="account-name">{{ request.user.username }}</span>
              <!-- <span class="account-description">Marketing Manager</span> -->
            </span>
          </button>
          <!-- /.btn-account -->
          <!-- .dropdown-aside -->
          <div id="dropdown-aside" class="dropdown-aside collapse">
            <a class="dropdown-item" href="{% url 'profile' user.username %}">{% trans 'Profile' %}</a>
            <!-- dropdown-items -->
            {% if request.user.is_authenticated %}

              <a class="dropdown-item" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>

            {% else %}

              <a class="dropdown-item" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>

            {% endif %}

            <a class="dropdown-item" href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a>
            <a class="dropdown-item" href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a>

            <!-- /dropdown-items -->
          </div>

          <!-- /.dropdown-aside -->
        </header>
        <!-- /.aside-header -->
        <!-- .aside-menu -->
        <section class="aside-menu has-scrollable">
          <!-- .stacked-menu -->
          <nav id="stacked-menu" class="stacked-menu">
            <!-- .menu -->
            <ul class="menu">
              <!-- .menu-item -->
              <li class="menu-item">
                <a href="/" class="menu-link">
                  <span class="menu-icon oi oi-dashboard"></span>
                  <span class="menu-text">Main</span>
                </a>
              </li>
              <li class="menu-item">
                <a href="{% url 'new_book' %}" class="menu-link">
                  <span class="menu-icon oi oi-dashboard"></span>
                  <span class="menu-text">Add a Book</span>
                </a>
              </li>
              <li class="menu-item">
                <a href="{% url 'log_pages' %}" class="menu-link">
                  <span class="menu-icon oi oi-dashboard"></span>
                  <span class="menu-text">Log or Edit Pages</span>
                </a>
              </li>
              <li class="menu-item">
                <a href="{% url 'log_dash' %}" class="menu-link">
                  <span class="menu-icon oi oi-dashboard"></span>
                  <span class="menu-text">Reading Log Dashboard</span>
                </a>
              </li>
              <li class="menu-item">
                <a href="{% url 'activity' %}" class="menu-link">
                  <span class="menu-icon oi oi-dashboard"></span>
                  <span class="menu-text">Activity</span>
                </a>
              </li>
              <li class="menu-item">
                <a href="{% url 'profile' user.username %}" class="menu-link">
                  <span class="menu-icon oi oi-dashboard"></span>
                  <span class="menu-text">Profile</span>
                </a>
              </li>
        </section>
        <!-- /.aside-menu -->
      </div>
      <!-- /.aside-content -->
    </aside>
    <!-- /.app-aside -->
    <!-- .app-main -->
    <main class="app-main">
      <!-- .wrapper -->
      <div class="wrapper">
        <!-- .page -->
        <div class="page">
          <!-- .page-inner -->
          <div class="page-inner">
            <!-- .page-title-bar -->
            <header class="page-title-bar">




            </header>
            <!-- /.page-title-bar -->
            <!-- .page-section -->
            <div class="page-section">
              {% block content %}

              {% endblock %}
            </div>
            <!-- /.page-section -->
          </div>
          <!-- /.page-inner -->
        </div>
        <!-- /.page -->
      </div>
      <!-- /.wrapper -->
    </main>
    <!-- /.app-main -->
  </div>
  <!-- /.app -->
  <!-- BEGIN BASE JS -->
  <!-- <script src="{% static '/looperassets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static '/looperassets/vendor/bootstrap/js/popper.min.js' %}"></script>
  <script src="{% static '/looperassets/vendor/bootstrap/js/bootstrap.min.js' %}"></script> -->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <!-- END BASE JS -->
  <!-- BEGIN PLUGINS JS -->
  <script src="{% static '/looperassets/vendor/stacked-menu/stacked-menu.min.js' %}"></script>
  <script src="{% static '/looperassets/vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
  <!-- <script src="{% static '/looperassets/vendor/masonry-layout/masonry.pkgd.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/flatpickr/flatpickr.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/nouislider/wNumb.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/nouislider/nouislider.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/blueimp-file-upload/js/vendor/jquery.ui.widget.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/blueimp-load-image/load-image.all.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/blueimp-canvas-to-blob/canvas-to-blob.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/blueimp-file-upload/js/jquery.iframe-transport.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/blueimp-file-upload/js/jquery.fileupload.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/blueimp-file-upload/js/jquery.fileupload-process.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/blueimp-file-upload/js/jquery.fileupload-image.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/blueimp-file-upload/js/jquery.fileupload-audio.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/blueimp-file-upload/js/jquery.fileupload-video.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/blueimp-file-upload/js/jquery.fileupload-validate.min.js' %}"></script> -->
   <!-- <script src="{% static '/looperassets/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js' %}"></script> -->
  <!-- BEGIN THEME JS -->
  <script src="{% static '/looperassets/javascript/main.min.js' %}"></script>

  <!-- <script src="{% static '/looperassets/javascript/pages/flatpickr-demo.js' %}"></script> -->
  <!-- <script src="{% static '/looperassets/javascript/pages/colorpicker-demo.js' %}"></script> -->
  <!-- <script src="{% static '/looperassets/javascript/pages/uploader-demo.js' %}"></script> -->
  <!-- <script src="{% static '/looperassets/javascript/pages/slider-demo.js' %}"></script> -->
  <!-- <script src="{% static '/looperassets/javascript/pages/spinner-demo.js' %}"></script> -->
  <!-- END THEME JS -->




</body>